services:
  backend:
    build:
      context: ./backend
    container_name: portfolio-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
